build:
  tests:
    override:
      -
        command: python -m pytest -m ''
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'
  dependencies:
      override:
        # update submodules (there are data from other our projects):
        - git submodule update --init --recursive ./submodule/

        - pip install -r requirements-dev.txt -q
        - python setup.py install

checks:
    python:
        code_rating: true
        duplicate_code: true
