build:
  tests:
    override:
      -
        command: python3 -m pytest
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'
  dependencies:
      override:
        - pip install -r requirements-dev.txt -q
        - pip install -r requirements.txt -q
