# =============================================================================
# Access Route4Me's logistics-as-a-service API
# using our Python SDK
#
# Copyright (C) 2016-2017 Route4Me
# =============================================================================

language: python

sudo: false

cache:
  pip: true

python:
  - "2.7"
  - "3.3"
  - "3.5"
  - nightly # currently points to 3.7-dev
  - pypy
  - pypy3

before_install:
  - pip install --upgrade pip ${PIP_FLAGS}
  - python setup.py install

install:
  - pip install -r requirements-dev.txt ${PIP_FLAGS}
  - pip install -r requirements.txt ${PIP_FLAGS}

  # we are going to send coverage only from Travis. So this package
  # is Travis-specific. We don't list this package in `requirements-dev.txt`
  - pip install codecov ${PIP_FLAGS}

  - pip --version
  - flake8 --version
  - pytest --version

script:
  - flake8
  - pytest -m ''
  - codecov

deploy:
  provider: pypi
  user: route4me
  password:
    secure: RAPnjiuSq+8//cPRDMvn1H77uJUyBGrLnpsmABSZKwnaz6e2Wu6qI464hDOYfDTZNslKygVJXZfW+EcXsvQtyv12cMPnnVU8UPJzVRlyfzSQzP4NbzxWmMP12peXY8IEfv3KYuv0w8gAHlvpgn/ERcT2dt8312YSKLqs5VMZP/8=
  on:
    tags: true                            # published only for tags
    python: "2.7"                         # published only for one NPM version
    repo: route4me/route4me-python-sdk    # published only from ONE repo
    distributions: sdist bdist_wheel
