# Maximum number of concurrent jobs for the project
max_jobs: 3

version: win.{build}-{branch}

# Test against the latest version of this Node.js version
environment:
  global:
    REQUIREMENTS_PATH: pip/libs
  matrix:
    # PYTHON VERSION are taken from https://www.appveyor.com/docs/build-environment/#python
    - PYTHON_VERSION: 27
    - PYTHON_VERSION: 33
    - PYTHON_VERSION: 35
    - PYTHON_VERSION: 36

# matrix:
#   allow_failures:
#     - PYTHON_VERSION: 36

init:
  - git config --global core.autocrlf true

cache:
  - pip/libs -> requirements.txt  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

pull_requests:
  do_not_increment_build_number: true


# Install scripts. (runs after repo cloning)
install:
  - set PATH=C:\Python%PYTHON_VERSION%;%REQUIREMENTS_PATH%;%PATH%
  - pip install --upgrade pip %PIP_FLAGS%
  - python setup.py install
  - pip install -r requirements-dev.txt %PIP_FLAGS% -t %REQUIREMENTS_PATH%
  - pip install -r requirements.txt %PIP_FLAGS% -t %REQUIREMENTS_PATH%


before_test:
  - pip --version
  - flake8 --version
  - pytest --version

test_script:
  - flake8
  - pytest -m ''

# Don't actually build.
build: off
