# Maximum number of concurrent jobs for the project
max_jobs: 3

version: win.{build}-{branch}

# Test against the latest version of this Node.js version
environment:
  global:
    # don't forget: this path should match with CACHE section
    REQUIREMENTS_SUBPATH: libs\
  matrix:
    # PYTHON VERSION are taken from https://www.appveyor.com/docs/build-environment/#python
    - PYTHON_VERSION: 26
    - PYTHON_VERSION: 27
    - PYTHON_VERSION: 33
    - PYTHON_VERSION: 35
    - PYTHON_VERSION: 36

# matrix:
#   allow_failures:
#     - PYTHON_VERSION: 36

init:
  - git config --global core.autocrlf true

cache:
  - libs\ -> requirements.txt  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

pull_requests:
  do_not_increment_build_number: true


# Install scripts. (runs after repo cloning)
install:
  - set PATH=C:\Python%PYTHON_VERSION%;%APPVEYOR_BUILD_FOLDER%\%REQUIREMENTS_SUBPATH%;%PATH%
  - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%\%REQUIREMENTS_SUBPATH%;%PYTHONPATH%

  - pip install --upgrade pip %PIP_FLAGS%
  - pip install --upgrade --force-reinstall -r requirements.txt %PIP_FLAGS% -t %APPVEYOR_BUILD_FOLDER%\%REQUIREMENTS_SUBPATH%
  - pip install --upgrade --force-reinstall -r requirements-dev.txt %PIP_FLAGS% -t %APPVEYOR_BUILD_FOLDER%\%REQUIREMENTS_SUBPATH%


before_test:
  - pip --version
  - python --version
  # - python -m flake8 --version
  - python -m pytest --version

test_script:
  # - python setup.py install

  - python -m flake8
  - python -m pytest -m ''

# Don't actually build.
build: off
